### ISSUE TITLE
pipewire with wireplumber selects wrong mic(s) as default

### ISSUE THREAD

**Issue by graygrotesque** [edisionnano/Screenshare-with-audio-on-Discord-with-Linux#21] opened 2022-07-16 10:14 UTC
Hello!

Thanks for the great guide, using it a lot! I'm using it with pipewire
I have an issue with wireplumber that is not happening with media-session.

When I used media-session and starting a stream it automatically selected the "virtmic" for the streamed window/game and when I switched a channel (ending the stream) my default mic vor my voice was always correctly selected.

since wireplumber however I can start a stream but the stream is not automtically selecting the virtmic. It uses my speaking mic as default and I have to manually select the virtmic in pavucontrol. Also, If I then close the stream and switch for example the server in another voice chat, now somehow the virtmic is the default mic and I have to manually switch it back to my speaking mic.

Is this solvable, has anyone else experienced this?

**Comment by edisionnano** [comment] 2022-07-18 15:44
Thanks for reporting this, I'll have to test

**Comment by edisionnano** [comment] 2022-07-30 16:18
I switched to wireplumber, sadly I couldn't reproduce. What distro do you use?

**Comment by graygrotesque** [comment] 2022-07-30 20:14
I'm using Arch
Thanks for testing! Maybe it's something here in my system then.

**Comment by Maciejka1** [comment] 2022-08-01 13:39
Same!

**Comment by edisionnano** [comment] 2022-08-02 08:03
Did you guys try opening an issue on the Wireplumber repository or ask at the PipeWire matrix server?

**Comment by maltejur** [comment] 2022-08-02 08:07
@edisionnano this could potentially be fixed by just adding a timeout in the right spot: https://github.com/maltejur/discord-screenaudio/commit/f01c941c9049eabda3a2f374335737ed6b16b6aa. I haven't done enough testing to confirm that this completely fixes the issue, but for some users [it is working](https://github.com/maltejur/discord-screenaudio/issues/28#issuecomment-1201907311).

**Comment by edisionnano** [comment] 2022-08-02 20:32
I may indeed end up adding half a second of delay

**Comment by edisionnano** [comment] 2022-08-03 04:48
Alright @Maciejka1 @graygrotesque I don't know whether this issue is reproducible each time or not but try adding
```await new Promise(r => setTimeout(r, 1000));```
somewhere around here
![image](https://user-images.githubusercontent.com/26039434/182526316-234558e5-c827-47d2-be33-a4386d6da178.png)

**Comment by graygrotesque** [comment] 2022-08-03 15:46
Hey! So I added the line and when I start screensharing, virtmic is now chosen!
But virtmic is broadcasting my mic instead of the created monitoring of the window I want to screenshare. So others hear me twi times.

So the created device is not sending the shared audio to virtmic but my mic instead.

**Comment by Maciejka1** [comment] 2022-08-03 22:03
@edisionnano works well now! thank you!

**Comment by edisionnano** [comment] 2022-08-04 15:39
I pushed the wait part, I can close this now. @graygrotesque you probably do something wrong when running virtmic, either way this issue can be closed

**Closed by edisionnano** 2022-08-04 15:39 UTC
